### ISSUE TITLE
Task 'upload' is not in your gulpfile

### ISSUE THREAD

**Issue by jitendravyas** [cworsley4/gulp-s3-ls#4]
I followed all instructions but getting this error

```
Task 'upload' is not in your gulpfile

```

**Comment by cworsley4** [comment]
Sorry, I should have been more clear on that on. Where I run "gulp upload
--dry" you should replace upload with your own task. That one was just an
example.

**Comment by jitendravyas** [comment]
This is my gulp file. I mean the part i copied from ur read me. I have added aws.json with keys too

```

var s3 = require("gulp-s3-ls");
var aws = require("./aws.json");

var options = { headers: {'Cache-Control': 'max-age=315360000, no-transform, public'} };

 gulp.task('upload', function () {

gulp.src('./dist/**', {read: false})
    .pipe(s3(aws, options));

})

```

**Comment by cworsley4** [comment]
So what isn't working exactly?

**Comment by cworsley4** [comment]
Any luck?
